org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.21.4
minecraft_version_range=[1.21.4,1.22)
forge_version=21.4.79-beta
forge_version_range=[21.4.79-beta,)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.4

## Mod Properties
mod_id=autoelytraflight
mod_name=AutoElytraFlight
archivesBaseName=AutoElytraFlight
mod_license=LGPL-3.0
mod_group_id=de.cheaterpaul.autoelytraflight
mod_authors=Cheaterpaul
mod_description=This mod will fly your elytra wings for you, and will gain altitude without the use of fireworks.
mod_credits
mod_issue_tracker_url=https://github.com/Cheaterpaul/AutoElytraFlight/issues
pack_format_number=18
main_version=2
major_version=0
minor_version=2
modrinth_id=GPL463SO
curseforge_id=666410
curseforge_slug=auto-elytra-flight