modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0"
issueTrackerURL = "https://github.com/Cheaterpaul/ElytraAutoFlight/issues"
[[mods]]
modId="elytraautoflight"
version="${version}"
displayName="Elytra Auto Flight"
logoFile="logo.png"
authors="Cheaterpaul"
description='''
This mod will fly your elytra wings for you, and will gain altitude without the use of fireworks.
'''
[[dependencies.elytraautoflight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.elytraautoflight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
