modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0"
issueTrackerURL = "https://github.com/Cheaterpaul/AutoElytraFlight/issues"
[[mods]]
modId="autoelytraflight"
version="${version}"
displayName="Auto Flight Elytra"
logoFile="logo.png"
authors="Cheaterpaul"
description='''
This mod will fly your elytra wings for you, and will gain altitude without the use of fireworks.
'''
[[dependencies.autoelytraflight]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autoelytraflight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
