modLoader="javafml"
loaderVersion="[43,)"
license="GPL-3.0"
issueTrackerURL = "https://github.com/Cheaterpaul/AutoElytraFlight/issues"
[[mods]]
modId="autoelytraflight"
version="${version}"
displayName="Auto Flight Elytra"
logoFile="logo.png"
authors="Cheaterpaul"
description='''
This mod will fly your elytra wings for you, and will gain altitude without the use of fireworks.
'''
[[dependencies.autoelytraflight]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.autoelytraflight]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},)"
    ordering="NONE"
    side="BOTH"
